version: '3.8'

services:
  redoc:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: redoc
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    command: uvicorn redoc.api:app --host 0.0.0.0 --port 8000 --reload
    
  # Add any additional services here, like a database or cache
  # redis:
  #   image: redis:alpine
  #   ports:
  #     - "6379:6379"

  # Test runner
  test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: redoc-test
    working_dir: /app
    environment:
      - PYTHONPATH=/app
    command: >
      sh -c "pytest tests/ -v --cov=redoc --cov-report=term-missing"
    depends_on:
      - redoc

  # Linting and code quality
  lint:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: redoc-lint
    working_dir: /app
    command: >
      sh -c "black --check . && \
             flake8 . && \
             mypy . && \
             bandit -r redoc/"
    volumes:
      - .:/app
