"""Basic example of using Redoc for document conversion."""

from pathlib import Path
from redoc import Redoc

def main():
    # Initialize Redoc
    converter = Redoc()
    
    # Create output directory if it doesn't exist
    output_dir = Path("output")
    output_dir.mkdir(exist_ok=True)
    
    # Example 1: Convert HTML to PDF
    html_content = """
    <!DOCTYPE html>
    <html>
    <head>
        <title>Sample Document</title>
        <style>
            body { font-family: Arial, sans-serif; line-height: 1.6; }
            h1 { color: #2c3e50; }
            .content { padding: 20px; }
        </style>
    </head>
    <body>
        <div class="content">
            <h1>Sample Document</h1>
            <p>This is a sample document generated by Redoc.</p>
            <p>Current time: {{ current_time }}</p>
        </div>
    </body>
    </html>
    """
    
    # Convert with template variables
    converter.convert(
        html_content,
        output_dir / "sample.pdf",
        format="html",
        current_time="2025-06-08 18:00:00"
    )
    print(f"Generated: {output_dir}/sample.pdf")

if __name__ == "__main__":
    main()
